apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: nginx
    spec:
      imagePullSecrets:
        - name: artifact-registry
      containers:
        - name: nginx
          image: asia-northeast1-docker.pkg.dev/sacred-lane-365413/kishi-reg/nginx:v1
          ports:
          - containerPort: 8080
          livenessProbe:
            httpGet:
              port: 8080
              path: /
            failureThreshold: 5
            periodSeconds: 5
      nodeSelector: # Podを乗せるノードをラベルから指定できる
        kubernetes.io/hostname: work01