kind: PersistentVolume
apiVersion: v1
metadata:
  name: mysql-pv-volume # Persistent Volumeの名前
  labels:
    type: local
spec:
  storageClassName: manual # Persistent Volume Claimと一致させる
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce # 1つのノードからread/writeでマウントできるモード
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
spec:
  # storageClassName = manual のPVを探してマウントする
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi # Persistent Volumeが持っている容量の内1GBを使用する
