apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  type: ClusterIP
  ports:
  - name: mysql
    port: 3306
    targetPort: 3306
    protocol: TCP
  # deploymentが管理するpodを定義
  # labelsにapp=mysqlと設定されたpodを管理する
  selector:
    app: mysql